'use client';
import { useEffect,useState } from 'react';
import './admin.css';
type Product={id:number;title:string;description:string;category:string;video_url:string|null;video_status:string;created_at:string;seller_user_id:number;name?:string;company?:string;email?:string};
export default function AdminPage(){const [products,setProducts]=useState<Product[]>([]);const [loading,setLoading]=useState(true);const [msg,setMsg]=useState('');
 async function load(){setLoading(true);const r=await fetch('/api/admin-products.php?status=review',{credentials:'include'});const d=await r.json().catch(()=>({}));if(r.ok)setProducts(d.products||[]);else setMsg(d.error||'Admin access required.');setLoading(false)}
 useEffect(()=>{void load()},[]);
 async function moderate(id:number,status:'published'|'rejected'){setMsg('');const r=await fetch('/api/admin-products.php',{method:'PATCH',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,status})});const d=await r.json().catch(()=>({}));if(!r.ok||!d.ok){setMsg(d.error||'Moderation failed.');return}setMsg(status==='published'?'Video approved and published.':'Video rejected.');void load()}
 return <main className="adminPage"><header><a className="brand" href="/marketplace/">BookMyMetal</a><strong>Admin · Video Moderation</strong><a href="/account/">Account</a></header><section className="adminHero"><span>CONTROL CENTER</span><h1>Review seller videos.</h1><p>Approve genuine seller media before it appears in the video-first marketplace.</p></section><section className="adminBody"><div className="adminHead"><div><h2>Pending review</h2><p>{products.length} video{products.length===1?'':'s'} waiting for moderation.</p></div><button onClick={()=>void load()}>Refresh</button></div>{msg&&<div className="adminMsg">{msg}</div>}{loading?<div className="empty">Loading moderation queue…</div>:products.length===0?<div className="empty"><b>Queue clear</b><span>No seller videos are waiting for review.</span></div>:<div className="queue">{products.map(p=><article className="reviewCard" key={p.id}><div className="reviewVideo">{p.video_url?<video src={p.video_url} controls playsInline preload="metadata"/>:<div>No video uploaded</div>}</div><div className="reviewInfo"><span className="tag">{p.category}</span><h3>{p.title}</h3><p>{p.description||'No description provided.'}</p><div className="seller"><b>{p.company||p.name||'Seller'}</b><span>{p.email||''}</span></div><div className="actions"><button className="approve" onClick={()=>void moderate(p.id,'published')}>✓ Approve & publish</button><button className="reject" onClick={()=>void moderate(p.id,'rejected')}>Reject</button></div></div></article>)}</div>}</section></main>}
