'use client'

import { useState } from 'react'

const videos = [
  { title: 'Investor Pitch', duration: '2:01', url: 'https://files2.heygen.ai/aws_pacific/avatar_tmp/1cbf34736a6c4e84a0ff4c7de37652e4/db6055f1f13052eb4619bd616c5df293.mp4', featured: true },
  { title: 'Investor & Partner Explainer', duration: '1:08', url: 'https://files2.heygen.ai/aws_pacific/avatar_tmp/1cbf34736a6c4e84a0ff4c7de37652e4/vcef78e873d1b4d2fa8af17330ff53aa2/eb60b7c8ca184167b1d0e54933a766b0.mp4' },
  { title: 'The Video-First Marketplace', duration: '1:16', url: 'https://files2.heygen.ai/aws_pacific/avatar_tmp/1cbf34736a6c4e84a0ff4c7de37652e4/v73ad9ac889f54d068dce9644bd641c53/b247431ef9f546ae8c10159c32287108.mp4' },
]

export default function Home() {
  const [playing, setPlaying] = useState(0)
  return <main className="pitchHome">
    <header className="pitchNav"><div className="pitchContainer"><a className="brand"><span className="brandMark">BM</span><span>BookMy<span>Metal</span></span></a><div className="pitchNavLinks"><a href="#opportunity">Opportunity</a><a href="#how">How it works</a><a href="#videos">Videos</a></div><a className="primary small" href="#join">Join us →</a></div></header>

    <section className="pitchHero"><div className="pitchContainer pitchHeroGrid"><div className="pitchHeroCopy"><div className="eyebrow"><span>●</span> BUILDING THE FUTURE OF METAL COMMERCE</div><h1>Metal commerce<br/><em>needs a new way.</em></h1><p>BookMyMetal is building a video-first B2B marketplace where buyers can discover real products, understand what they are buying, connect with sellers and move from discovery to business.</p><div className="pitchActions"><a className="primary" href="#videos">▶ Watch the pitch</a><a className="secondary" href="#join">Join as an early seller</a></div><div className="pitchProof"><span>●</span> Early-stage opportunity · India · Marketplace</div></div><div className="pitchHeroVideo"><video controls playsInline preload="metadata" poster="https://files2.heygen.ai/aws_pacific/avatar_tmp/1cbf34736a6c4e84a0ff4c7de37652e4/db6055f1f13052eb4619bd616c5df293.jpeg"><source src={videos[0].url} type="video/mp4"/></video><div className="videoBadge">BOOKMYMETAL INVESTOR PITCH · 2:01</div></div></div></section>

    <section id="opportunity" className="pitchSection"><div className="pitchContainer"><div className="sectionIntro"><span className="kicker">THE OPPORTUNITY</span><h2>The way metal is bought is still<br/><em>stuck in the past.</em></h2><p>Buyers often move between catalogues, photos, calls, WhatsApp messages and quotations. Sellers have great products, but limited digital reach and no simple way to show them at their best.</p></div><div className="problemGrid"><div><strong>01</strong><h3>Hard to discover</h3><p>Thousands of products and suppliers are fragmented across the market.</p></div><div><strong>02</strong><h3>Hard to understand</h3><p>Specs, finish, quality and capability are difficult to judge from static listings.</p></div><div><strong>03</strong><h3>Hard to connect</h3><p>Buyers and sellers still rely heavily on manual conversations and follow-ups.</p></div></div></div></section>

    <section id="how" className="pitchDark"><div className="pitchContainer"><div className="sectionIntro light"><span className="kicker">THE BOOKMYMETAL IDEA</span><h2>See the metal.<br/><em>Know the deal.</em></h2><p>Video becomes the front door to B2B metal commerce — making products easier to discover, sellers easier to trust and buying easier to start.</p></div><div className="flow"><div><b>01</b><span>DISCOVER</span><small>Find products and suppliers</small></div><i>→</i><div><b>02</b><span>WATCH</span><small>See real products in action</small></div><i>→</i><div><b>03</b><span>COMPARE</span><small>Evaluate specifications & sellers</small></div><i>→</i><div><b>04</b><span>ENQUIRE</span><small>Connect and start business</small></div><i>→</i><div><b>05</b><span>BUY</span><small>Move toward transactions</small></div></div></div></section>

    <section id="videos" className="pitchSection"><div className="pitchContainer"><div className="sectionIntro"><span className="kicker">WATCH THE VISION</span><h2>Don't just read about it.<br/><em>See it.</em></h2></div><div className="videoGrid">{videos.map((v, i) => <div className={'pitchVideoCard '+(playing === i ? 'selected' : '')} key={v.title} onClick={() => setPlaying(i)}><video controls playsInline preload="metadata"><source src={v.url} type="video/mp4"/></video><div className="videoCardMeta"><b>{v.title}</b><span>{v.duration}</span></div></div>)}</div></div></section>

    <section className="opportunityBanner"><div className="pitchContainer"><span className="kicker">WHY JOIN EARLY?</span><h2>Help build the marketplace<br/><em>before everyone else.</em></h2><div className="joinBenefits"><div><b>🏭 Early sellers</b><span>Get a first-mover presence and help shape the seller experience.</span></div><div><b>🤝 Strategic partners</b><span>Bring technology, distribution, logistics or industry expertise.</span></div><div><b>💰 Investors</b><span>Join the conversation around a new B2B commerce opportunity.</span></div></div></div></section>

    <section id="join" className="joinSection"><div className="pitchContainer joinGrid"><div><span className="kicker">LET'S BUILD IT TOGETHER</span><h2>Be part of<br/><em>BookMyMetal.</em></h2><p>We are opening conversations with early sellers, strategic partners, founding team members and investors who believe metal commerce can be better.</p></div><div className="joinCards"><a href="mailto:hello@bookmymetal.com?subject=Early%20Seller%20-%20BookMyMetal"><span>🏭</span><b>Become an Early Seller</b><small>Put your products on the first wave of the marketplace →</small></a><a href="mailto:hello@bookmymetal.com?subject=Investor%20-%20BookMyMetal"><span>💰</span><b>Talk to us about investing</b><small>Request the investor conversation →</small></a><a href="mailto:hello@bookmymetal.com?subject=Founding%20Team%20-%20BookMyMetal"><span>🤝</span><b>Join the founding journey</b><small>Explore team and strategic roles →</small></a></div></div></section>

    <footer className="pitchFooter"><div className="pitchContainer"><div className="brand"><span className="brandMark">BM</span><span>BookMy<span>Metal</span></span></div><p>Video-first B2B metal commerce.</p><span>© 2026 BookMyMetal</span></div></footer>
  </main>
}
