'use client'

import { ChangeEvent, FormEvent, useRef, useState } from 'react'
import { resolveCategory, marketplaceCategories } from './category-data'
import './marketplace.css'

type Result={id:string;title:string;type:string;category:string;seller:string;location:string;specs:string[];score?:number}
const categoryVisuals=[
 {name:'PPGL Roofing Sheets',slug:'ppgl-roofing-sheets',art:'roofing'}, {name:'Steel Coils',slug:'steel-coils',art:'coil'}, {name:'Structural Fabrication',slug:'structural-fabrication',art:'fabrication'}, {name:'MS / GI Pipes',slug:'ms-gi-pipes',art:'pipes'}, {name:'Industrial Machines',slug:'industrial-machines',art:'machines'}, {name:'Furniture',slug:'furniture',art:'furniture'}
]
function MicIcon(){return <svg viewBox="0 0 24 24" aria-hidden="true"><rect x="9" y="3" width="6" height="11" rx="3"/><path d="M5 11a7 7 0 0 0 14 0M12 18v3M8 21h8"/></svg>}
function ImageIcon(){return <svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="4" width="18" height="16" rx="2"/><circle cx="8.5" cy="9" r="1.5"/><path d="m4 17 5-5 3 3 2-2 6 6"/></svg>}
function SearchIcon(){return <svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="10.8" cy="10.8" r="6.8"/><path d="m16 16 5 5"/></svg>}
function CategoryArt({kind}:{kind:string}){return <div className={`categoryArt ${kind}`}><span>✦</span><i/><b/></div>}

export default function MarketplacePage(){
 const [query,setQuery]=useState(''); const [submitted,setSubmitted]=useState(''); const [mode,setMode]=useState('text'); const [imageName,setImageName]=useState(''); const [listening,setListening]=useState(false); const [language,setLanguage]=useState('English'); const [results,setResults]=useState<Result[]>([]); const fileRef=useRef<HTMLInputElement>(null)
 const submit=async(e?:FormEvent)=>{e?.preventDefault();const q=query.trim();const category=resolveCategory(q);if(category){window.location.href=`/categories/?q=${encodeURIComponent(category.name)}`;return}setSubmitted(q||'All metal products & services');const r=await fetch(`/api/search?q=${encodeURIComponent(q)}`).then(x=>x.json()).catch(()=>({results:[]}));setResults(r.results||[])}
 const chooseImage=(e:ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(f){setImageName(f.name);setMode('image');setSubmitted('Visual search: '+f.name);setResults([])}}
 const voiceSearch=()=>{setMode('voice');setListening(true);setTimeout(()=>{setListening(false);const q='0.50 mm blue PPGL roofing sheet near Bangalore';setQuery(q);submitQuery(q)},900)}
 const submitQuery=async(q:string)=>{const category=resolveCategory(q);if(category){window.location.href=`/categories/?q=${encodeURIComponent(category.name)}`;return}setSubmitted(q);const d=await fetch(`/api/search?q=${encodeURIComponent(q)}`).then(r=>r.json()).catch(()=>({results:[]}));setResults(d.results||[])}
 return <main className="marketplace">
  <header className="marketHeader"><a className="bmBrand" href="/"><span className="bmMark">BM</span><span>BookMy<span>Metal</span></span></a><nav><a className="active" href="/marketplace/">Marketplace</a><a href="/categories/">Categories</a><a href="/suppliers/">Suppliers</a><a href="/rfq/">My RFQs</a></nav><div className="headerActions"><label className="language"><span>Language</span><select value={language} onChange={e=>setLanguage(e.target.value)} aria-label="Language"><option>English</option><option>ಕನ್ನಡ · Kannada</option><option>हिन्दी · Hindi</option><option>தமிழ் · Tamil</option><option>తెలుగు · Telugu</option><option>मराठी · Marathi</option></select></label><a href="/account/">Sign in</a><a className="headerCta" href="/seller/">Sell on BookMyMetal</a></div></header>
  <section className="marketHero"><div className="heroCopy"><span className="marketEyebrow">THE VIDEO-FIRST B2B MARKETPLACE</span><h1>See it.<br/><em>Understand it.</em><br/>Source it.</h1><p>Find metal products, suppliers and industrial services through real visual content — then compare, enquire or buy.</p></div><div className="heroVisual"><div className="heroVideoMock"><div className="play">▶</div><span>VIDEO-FIRST COMMERCE</span><strong>Real product. Real capability.</strong></div></div></section>
  <section className="searchSection"><form className="aiSearch" onSubmit={submit}><div className="searchLead"><SearchIcon/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="What product or service do you need? Try “furniture”" aria-label="Search BookMyMetal"/></div><button type="button" className={'searchMode '+(listening?'on':'')} onClick={voiceSearch}><MicIcon/>{listening?'Listening…':'Speak'}</button><button type="button" className={'searchMode '+(mode==='image'?'on':'')} onClick={()=>fileRef.current?.click()}><ImageIcon/>Image</button><input ref={fileRef} hidden type="file" accept="image/*" onChange={chooseImage}/><button className="searchGo" type="submit">Search</button></form><div className="searchHint">AI Search · Type naturally, speak a request, or upload a product image</div><div className="chips">{marketplaceCategories.slice(0,6).map(c=><button key={c.slug} type="button" onClick={()=>window.location.href=`/categories/?q=${encodeURIComponent(c.name)}`}>{c.name}</button>)}</div></section>
  {imageName&&<div className="imageNotice"><ImageIcon/><span>Image selected: <b>{imageName}</b> · visual matching will be connected to AI vision.</span></div>}
  <section className="categoryShowcase"><div className="sectionTop"><div><span className="marketEyebrow">EXPLORE VISUALLY</span><h2>Find your category faster.</h2></div><a href="/categories/">View all categories →</a></div><div className="categoryGrid">{categoryVisuals.map(c=><a key={c.slug} href={`/categories/?q=${encodeURIComponent(c.name)}`} className="categoryCard"><CategoryArt kind={c.art}/><div><strong>{c.name}</strong><span>Explore →</span></div></a>)}</div></section>
  <section className="marketBody"><div className="sectionTop"><div><span className="marketEyebrow">{submitted?'SEARCH RESULTS':'DISCOVER'}</span><h2>{submitted?`Results for “${submitted}”`:'Watch products. Understand suppliers.'}</h2></div><div className="filters"><button>All</button><button>Products</button><button>Services</button><button>Manufacturers</button></div></div>{results.length?<div className="resultGrid">{results.map(r=><article className="resultCard" key={r.id}><div className="resultVideo"><span>{r.type.toUpperCase()}</span><div className="play small">▶</div><small>Seller product video</small></div><div className="resultInfo"><h3>{r.title}</h3><b>{r.seller}</b><p>{r.specs.join(' · ')} · {r.location}</p><div className="cardActions"><button>Watch</button><button>Compare</button><button>Request quote</button></div></div></article>)}</div>:<div className="emptyState"><strong>Search the marketplace</strong><span>Try “furniture”, “PPGL roofing sheets” or any product/service.</span></div>}</section>
  <section className="aiJourney"><div><span className="marketEyebrow">ONE SEARCH. MULTIPLE INPUTS.</span><h2>Search the way<br/>you think.</h2><p>BookMyMetal is being built around natural buying intent — not rigid catalogue keywords.</p></div><div className="journeySteps"><div><b>⌨</b><strong>Type</strong><span>“Need 5,000 sq ft blue PPGL…”</span></div><div><b>🎙</b><strong>Speak</strong><span>Describe the requirement naturally.</span></div><div><b>⌁</b><strong>Image</strong><span>Show us what you need.</span></div><div><b>✦</b><strong>AI understands</strong><span>Match intent, specs and suppliers.</span></div></div></section>
  <section className="how"><span className="marketEyebrow">THE JOURNEY</span><h2>Discover → Watch → Understand → Compare → Quote / Order</h2><div className="journeyBar"><span>01 Discover</span><span>02 Watch</span><span>03 Understand</span><span>04 Compare / RFQ</span><span>05 Order</span><span>06 Track</span></div></section>
  <footer className="marketFooter"><div><a className="bmBrand" href="/"><span className="bmMark">BM</span><span>BookMy<span>Metal</span></span></a><p>Video-first B2B metal commerce.</p></div><div><b>Marketplace</b><a href="/categories/">Categories</a><a href="/suppliers/">Suppliers</a><a href="/rfq/">Request Quote</a></div><div><b>For sellers</b><a href="/seller/">Seller workspace</a><a href="/seller/">Upload products</a></div></footer>
 </main>
}
