'use client'
import { ChangeEvent, FormEvent, useEffect, useMemo, useRef, useState } from 'react'
import { resolveCategory, marketplaceCategories } from './category-data'
import './marketplace.css'
type Result={id:string;title:string;type:string;category:string;seller:string;location:string;specs:string[];score?:number;video_url?:string|null;video_status?:string}
const categoryVisuals=[{name:'PPGL Roofing Sheets',slug:'ppgl-roofing-sheets',art:'roofing'},{name:'Steel Coils',slug:'steel-coils',art:'coil'},{name:'Structural Fabrication',slug:'structural-fabrication',art:'fabrication'},{name:'MS / GI Pipes',slug:'ms-gi-pipes',art:'pipes'},{name:'Industrial Machines',slug:'industrial-machines',art:'machines'},{name:'Furniture',slug:'furniture',art:'furniture'}]
function MicIcon(){return <svg viewBox="0 0 24 24"><rect x="9" y="3" width="6" height="11" rx="3"/><path d="M5 11a7 7 0 0 0 14 0M12 18v3M8 21h8"/></svg>};function ImageIcon(){return <svg viewBox="0 0 24 24"><rect x="3" y="4" width="18" height="16" rx="2"/><circle cx="8.5" cy="9" r="1.5"/><path d="m4 17 5-5 3 3 2-2 6 6"/></svg>};function SearchIcon(){return <svg viewBox="0 0 24 24"><circle cx="10.8" cy="10.8" r="6.8"/><path d="m16 16 5 5"/></svg>};function CloseIcon(){return <span>×</span>};function CategoryArt({kind}:{kind:string}){return <div className={`categoryArt ${kind}`}><span>✦</span><i/><b/></div>}
export default function MarketplacePage(){
 const [query,setQuery]=useState(''),[submitted,setSubmitted]=useState(''),[mode,setMode]=useState('text'),[imageName,setImageName]=useState(''),[listening,setListening]=useState(false),[language,setLanguage]=useState('English'),[results,setResults]=useState<Result[]>([]),[filter,setFilter]=useState('All'),[recent,setRecent]=useState<string[]>([]),[modal,setModal]=useState<'rfq'|'compare'|'watch'|null>(null),[selected,setSelected]=useState<Result[]>([]),[activeResult,setActiveResult]=useState<Result|null>(null),[rfqStatus,setRfqStatus]=useState(''),[rfqBusy,setRfqBusy]=useState(false),[cartCount,setCartCount]=useState(0);const fileRef=useRef<HTMLInputElement>(null)
 useEffect(()=>{try{setRecent(JSON.parse(localStorage.getItem('bmm_recent_searches')||'[]'));setCartCount(JSON.parse(localStorage.getItem('bmm_cart')||'[]').length)}catch{}},[])
 const filteredResults=useMemo(()=>filter==='All'?results:results.filter(r=>filter==='Products'?r.type==='product':filter==='Services'?r.type==='service':filter==='Manufacturers'),[results,filter])
 const saveRecent=(q:string)=>{if(!q)return;const next=[q,...recent.filter(x=>x.toLowerCase()!==q.toLowerCase())].slice(0,5);setRecent(next);try{localStorage.setItem('bmm_recent_searches',JSON.stringify(next))}catch{}}
 const addToCart=(r:Result)=>{try{const current=JSON.parse(localStorage.getItem('bmm_cart')||'[]');const next=current.some((x:Result)=>x.id===r.id)?current:[...current,{id:r.id,title:r.title,category:r.category,seller:r.seller,quantity:''}];localStorage.setItem('bmm_cart',JSON.stringify(next));setCartCount(next.length)}catch{}}
 const runSearch=async(q:string)=>{const clean=q.trim(),category=resolveCategory(clean);if(category){window.location.href=`/categories/?q=${encodeURIComponent(category.name)}`;return}setSubmitted(clean||'All metal products & services');setFilter('All');saveRecent(clean);const d=await fetch(`/api/search?q=${encodeURIComponent(clean)}`).then(r=>r.json()).catch(()=>({results:[]}));setResults(d.results||[])}
 const submit=(e?:FormEvent)=>{e?.preventDefault();void runSearch(query)}
 const chooseImage=(e:ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(f){setImageName(f.name);setMode('image');setSubmitted('Visual search: '+f.name);setResults([])}}
 const voiceSearch=()=>{setMode('voice');setListening(true);setTimeout(()=>{setListening(false);const q='0.50 mm blue PPGL roofing sheet near Bangalore';setQuery(q);void runSearch(q)},900)}
 const toggleCompare=(r:Result)=>setSelected(s=>s.some(x=>x.id===r.id)?s.filter(x=>x.id!==r.id):[...s,r].slice(-3));const openRfq=(r:Result)=>{setActiveResult(r);setRfqStatus('');setModal('rfq')}
 const sendRfq=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setRfqBusy(true);const fd=new FormData(e.currentTarget);const payload={name:String(fd.get('name')||''),company:String(fd.get('company')||''),email:String(fd.get('email')||''),phone:String(fd.get('phone')||''),product:activeResult?.title||submitted,category:activeResult?.category||'',message:String(fd.get('message')||'')};const d=await fetch('/api/rfq.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}).then(r=>r.json()).catch(()=>({ok:false,error:'Network error'}));setRfqBusy(false);setRfqStatus(d.ok?`RFQ submitted successfully. Reference #${d.rfq_id}.`:(d.error||'Unable to submit RFQ.'));if(d.ok)e.currentTarget.reset()}
}
