'use client';
import { FormEvent, useState } from 'react';
import './seller.css';

export default function SellerPage(){
 const [title,setTitle]=useState(''); const [category,setCategory]=useState('PPGL Roofing Sheets'); const [description,setDescription]=useState(''); const [video,setVideo]=useState<File|null>(null); const [status,setStatus]=useState(''); const [busy,setBusy]=useState(false);
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setStatus('');try{const r=await fetch('/api/seller-product.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({seller_user_id:1,title,category,description,video_url:video?.name||''})});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||'Unable to save product');setStatus(`Product #${d.product_id} submitted for review.`);setTitle('');setDescription('');setVideo(null);}catch(err){setStatus(err instanceof Error?err.message:'Unable to connect.')}finally{setBusy(false)}}
 return <main className="seller-page"><header><a href="/marketplace/" className="brand">BookMyMetal</a><span>Seller Workspace</span><a href="/account/">Account</a></header><section className="seller-hero"><span className="eyebrow">SELLER WORKSPACE</span><h1>Turn your products into<br/><em>video-first listings.</em></h1><p>Publish what you make, show how it works and let buyers discover, compare and request quotes.</p></section><section className="workspace"><aside><div className="side active">＋ Add product</div><div className="side">Products</div><div className="side">Enquiries</div><div className="side">Orders</div><div className="side">Analytics</div></aside><div className="panel"><div className="panel-head"><div><h2>Add a product</h2><p>Start with the core information. Video publishing and moderation are the next media layer.</p></div><span className="badge">VIDEO-FIRST</span></div><form onSubmit={submit}><label>Product title<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. 0.50 mm Blue PPGL Roofing Sheet" required /></label><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}><option>PPGL Roofing Sheets</option><option>Steel Coils & Slitting</option><option>Structural Fabrication</option><option>Industrial Machines</option><option>Other</option></select></label><label>Description<textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Tell buyers what they should understand from your listing." rows={5}/></label><label>Product video<input type="file" accept="video/mp4,video/webm,video/quicktime" onChange={e=>setVideo(e.target.files?.[0]||null)}/><small>{video ? video.name : 'MP4 / WebM / MOV · upload pipeline will be connected next'}</small></label><button className="primary" disabled={busy}>{busy?'Saving…':'Save & submit for review'}</button></form>{status&&<div className="status">{status}</div>}</div></section></main>;
}
