'use client';
import { FormEvent, useEffect, useState } from 'react';
import './seller.css';

type User={id:number;email:string;name?:string;company?:string;role:'buyer'|'seller'|'admin'};
type Product={id:number;title:string;description?:string|null;category:string;video_url?:string|null;video_status:string;created_at:string};

export default function SellerPage(){
 const [user,setUser]=useState<User|null>(null); const [checking,setChecking]=useState(true); const [products,setProducts]=useState<Product[]>([]); const [loadingProducts,setLoadingProducts]=useState(false);
 const [title,setTitle]=useState(''); const [category,setCategory]=useState('PPGL Roofing Sheets'); const [description,setDescription]=useState(''); const [video,setVideo]=useState<File|null>(null); const [status,setStatus]=useState(''); const [busy,setBusy]=useState(false);
 const loadProducts=async()=>{setLoadingProducts(true);try{const r=await fetch('/api/seller-products.php',{credentials:'include'});const d=await r.json();if(r.ok&&d.ok)setProducts(d.products||[])}catch{}finally{setLoadingProducts(false)}};
 useEffect(()=>{fetch('/api/session.php?action=me',{credentials:'include'}).then(async r=>r.ok?r.json():null).then(async d=>{if(d?.user?.role==='seller'){setUser(d.user);await loadProducts()}}).catch(()=>{}).finally(()=>setChecking(false))},[]);
 async function submit(e:FormEvent){e.preventDefault();if(!user)return;setBusy(true);setStatus('');try{const fd=new FormData();fd.append('title',title);fd.append('category',category);fd.append('description',description);if(video)fd.append('video',video);const r=await fetch('/api/seller-product.php',{method:'POST',credentials:'include',body:fd});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||'Unable to save product');setStatus(`Product #${d.product_id} submitted${d.video_status==='review'?' with video for review':''}.`);setTitle('');setDescription('');setVideo(null);await loadProducts()}catch(err){setStatus(err instanceof Error?err.message:'Unable to connect.')}finally{setBusy(false)}}
 if(checking)return <main className="seller-page"><div className="seller-loading">Checking seller account…</div></main>;
 if(!user)return <main className="seller-page"><header><a href="/marketplace/" className="brand">BookMyMetal</a><span>Seller Workspace</span><a href="/account/">Account</a></header><section className="seller-hero"><span className="eyebrow">SELLER ACCESS</span><h1>Sign in to your<br/><em>seller workspace.</em></h1><p>Seller accounts can publish products, submit videos for review and manage buyer enquiries.</p><a className="primary" href="/account/">Sign in / Create seller account</a></section></main>;
 return <main className="seller-page"><header><a href="/marketplace/" className="brand">BookMyMetal</a><span>Seller Workspace</span><a href="/account/">{user.company||user.name||'Account'}</a></header><section className="seller-hero"><span className="eyebrow">SELLER WORKSPACE</span><h1>Turn your products into<br/><em>video-first listings.</em></h1><p>Publish what you make, show how it works and let buyers discover, compare and request quotes.</p></section><section className="workspace"><aside><div className="side active">＋ Add product</div><div className="side">Products <b>{products.length}</b></div><div className="side">Enquiries</div><div className="side">Orders</div><div className="side">Analytics</div></aside><div className="panel"><div className="panel-head"><div><h2>Add a product</h2><p>Upload the real seller video. New videos enter review before buyers see them.</p></div><span className="badge">VIDEO-FIRST</span></div><form onSubmit={submit}><label>Product title<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. 0.50 mm Blue PPGL Roofing Sheet" required /></label><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}><option>PPGL Roofing Sheets</option><option>Steel Coils & Slitting</option><option>Structural Fabrication</option><option>Industrial Machines</option><option>Other</option></select></label><label>Description<textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Tell buyers what they should understand from your listing." rows={5}/></label><label>Product video<input type="file" accept="video/mp4,video/webm,video/quicktime" onChange={e=>setVideo(e.target.files?.[0]||null)}/><small>{video ? `${video.name} · ${(video.size/1024/1024).toFixed(1)} MB` : 'MP4 / WebM / MOV · maximum 100 MB'}</small></label><button className="primary" disabled={busy}>{busy?'Uploading…':'Upload & submit for review'}</button></form>{status&&<div className="status">{status}</div>}
 <div className="productManager"><div className="managerHead"><div><h2>My products</h2><p>Track every listing and its video review status.</p></div><button onClick={loadProducts} disabled={loadingProducts}>{loadingProducts?'Refreshing…':'Refresh'}</button></div>{products.length===0?<div className="managerEmpty">No products yet. Upload your first video-first listing above.</div>:<div className="sellerProductList">{products.map(p=><article className="sellerProduct" key={p.id}><div className="sellerProductMedia">{p.video_url?<video src={p.video_url} controls playsInline preload="metadata"/>:<span>No video</span>}</div><div className="sellerProductInfo"><div className="productTop"><span className="productId">#{p.id}</span><span className={`statusBadge ${p.video_status}`}>{p.video_status}</span></div><h3>{p.title}</h3><p>{p.category}</p>{p.description&&<small>{p.description}</small>}<div className="productDate">Added {new Date(p.created_at).toLocaleDateString()}</div></div></article>)}</div>}</div>
 </div></section></main>;
}
