<?php
declare(strict_types=1);
require_once __DIR__ . '/db.php';
require_once __DIR__ . '/user-schema.php';
session_set_cookie_params(['lifetime'=>0,'path'=>'/','secure'=>!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off','httponly'=>true,'samesite'=>'Lax']);
if(session_status()!==PHP_SESSION_ACTIVE)session_start();
header('Content-Type: application/json; charset=utf-8');
$origin=$_SERVER['HTTP_ORIGIN']??'';if($origin==='https://www.bookmymetal.com')header('Access-Control-Allow-Origin: https://www.bookmymetal.com');header('Access-Control-Allow-Credentials: true');header('Access-Control-Allow-Headers: Content-Type');header('Access-Control-Allow-Methods: POST, OPTIONS');if($_SERVER['REQUEST_METHOD']==='OPTIONS')exit;if($_SERVER['REQUEST_METHOD']!=='POST'){http_response_code(405);echo json_encode(['ok'=>false,'error'=>'Method not allowed']);exit;}
$pdo->exec("CREATE TABLE IF NOT EXISTS users (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,email VARCHAR(190) NOT NULL UNIQUE,password_hash VARCHAR(255) NOT NULL,role ENUM('buyer','seller','admin') NOT NULL DEFAULT 'buyer',name VARCHAR(120) NULL,company VARCHAR(190) NULL,email_verified TINYINT(1) NOT NULL DEFAULT 0,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
ensure_user_auth_schema($pdo);
$input=json_decode(file_get_contents('php://input'),true)?:[];$action=(string)($input['action']??'login');
if($action==='register'){$email=strtolower(trim((string)($input['email']??'')));$password=(string)($input['password']??'');$name=trim((string)($input['name']??''));$company=trim((string)($input['company']??''));if(!filter_var($email,FILTER_VALIDATE_EMAIL)||$name===''||strlen($password)<8){http_response_code(422);echo json_encode(['ok'=>false,'error'=>'Enter your name, a valid email and a password of at least 8 characters.']);exit;}try{$s=$pdo->prepare("INSERT INTO users(email,password_hash,role,name,company,role_confirmed,seller_enabled) VALUES(?,?, 'buyer',?,?,1,0)");$s->execute([$email,password_hash($password,PASSWORD_DEFAULT),$name,$company?:null]);$id=(int)$pdo->lastInsertId();session_regenerate_id(true);$_SESSION['user']=['id'=>$id,'email'=>$email,'phone'=>null,'role'=>'buyer','seller_enabled'=>false,'name'=>$name,'company'=>$company?:null,'role_confirmed'=>true];echo json_encode(['ok'=>true,'user'=>$_SESSION['user'],'message'=>'Account created and signed in.']);}catch(PDOException $e){http_response_code(409);echo json_encode(['ok'=>false,'error'=>'An account with this email already exists.']);}exit;}
if($action==='login'){$email=strtolower(trim((string)($input['email']??'')));$password=(string)($input['password']??'');if(!filter_var($email,FILTER_VALIDATE_EMAIL)||$password===''){http_response_code(422);echo json_encode(['ok'=>false,'error'=>'Enter your email and password.']);exit;}$s=$pdo->prepare('SELECT id,email,phone,password_hash,role,name,company,role_confirmed,seller_enabled FROM users WHERE email=? LIMIT 1');$s->execute([$email]);$u=$s->fetch();if(!$u||!password_verify($password,$u['password_hash'])){http_response_code(401);echo json_encode(['ok'=>false,'error'=>'Invalid email or password.']);exit;}session_regenerate_id(true);$_SESSION['user']=['id'=>(int)$u['id'],'email'=>$u['email'],'phone'=>$u['phone'],'role'=>$u['role'],'seller_enabled'=>user_can_sell($u),'name'=>$u['name'],'company'=>$u['company'],'role_confirmed'=>(bool)$u['role_confirmed']];echo json_encode(['ok'=>true,'user'=>$_SESSION['user']]);exit;}
http_response_code(400);echo json_encode(['ok'=>false,'error'=>'Unsupported action']);
